import { Ionicons } from '@expo/vector-icons';
import { Tabs } from "expo-router";
import React from 'react';
import './globals.css';

export default function RootLayout() {
  return (
    <Tabs
      screenOptions={{
        tabBarActiveTintColor: '#3b82f6', // blue-500
        tabBarInactiveTintColor: '#6b7280', // gray-500
        tabBarStyle: {
          backgroundColor: '#f9fafb', // gray-50
        },
      }}
    >
      <Tabs.Screen
        name="screens/HomeScreen"
        options={{
          title: 'Home',
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="home" size={size} color={color} />
          ),
          headerShown: false,
        }}
      />
      <Tabs.Screen
        name="screens/CreateTrainingSetScreen"
        options={{
          title: 'Create',
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="add-circle" size={size} color={color} />
          ),
          headerShown: false,
        }}
      />

      {/* Hide autogenerated HomeScreen tab */}
      <Tabs.Screen name="index" options={{ href: null }} />
      <Tabs.Screen name="screens/TimerScreen" options={{ href: null }} />
    </Tabs>
  );
}
